export const VARIABLE_CONFIG = [
  {
    label: "系统变量",
    value: "systemVar",
    children: [
      { label: "编号（一 二 三...）", value: "itemNumber" },
      { label: "编号（1 2 3...）", value: "orderNumber" },
    ],
  },
  {
    label: "系统函数",
    value: "systemFunc",
    children: [
      { label: "IF（判断）", value: "ifFunc" },
      { label: "LOOP（循环函数）", value: "loopFunc" },
      { label: "JOIN（循环函数）", value: "joinFunc" },
    ],
  },
  {
    label: "借款人信息（个人）",
    value: "customerInfo",
    children: [
      { label: "客户名称", value: "customerName" },
      { label: "性别", value: "gender" },
      { label: "民族", value: "nation" },
      { label: "出生年", value: "birthYear" },
      { label: "出生月", value: "birthMonth" },
      { label: "出生日", value: "birthDay" },
      { label: "证件号码", value: "idNumber" },
      { label: "身份证地址", value: "idAddress" },
      { label: "通讯地址", value: "contactAddress" },
      { label: "联系电话", value: "phone" },
    ],
  },
  {
    label: "借款人信息（企业）",
    value: "enterpriseInfo",
    children: [
      { label: "企业名称", value: "enterpriseName" },
      { label: "统一社会信用代码", value: "unifiedSocialCreditCode" },
      { label: "注册地址", value: "registeredAddress" },
      { label: "通讯地址", value: "contactAddress" },
      { label: "联系电话", value: "phone" },
      { label: "法定代表人姓名", value: "legalName" },
      { label: "法定代表人联系电话", value: "legalPhone" },
    ],
  },
  {
    label: "担保人信息（个人）",
    value: "guarantorInfoList",
    children: [
      { label: "担保人名称", value: "guarantorName" },
      { label: "性别", value: "gender" },
      { label: "民族", value: "nation" },
      { label: "出生年", value: "birthYear" },
      { label: "出生月", value: "birthMonth" },
      { label: "出生日", value: "birthDay" },
      { label: "担保人证件号码", value: "idNumber" },
      { label: "身份证地址", value: "idAddress" },
      { label: "通讯地址", value: "contactAddress" },
      { label: "联系电话", value: "phone" },
      { label: "借款人名称", value: "customerName" },
      { label: "授信单号", value: "credits.creditNo" },
      { label: "资方名称", value: "credits.funderFullName" },
      { label: "委托担保合同号", value: "credits.guaranteeNo" },
      { label: "委托担保合同名称", value: "credits.guaranteeNoName" },
      { label: "委托担保签订日期", value: "credits.guaranteeSignDate" },
      { label: "担保期限", value: "credits.guaranteePeriod" },
      { label: "最高担保额", value: "credits.maxGuaranteeAmount" },
      { label: "被告顺序", value: "defendantNumber" },
    ],
  },
  {
    label: "业务信息汇总",
    value: "summaryInfo",
    children: [
      { label: "借款人姓名", value: "customerName" },
      { label: "借款人类型", value: "borrowerType" },
      { label: "债权人", value: "debtHolder" },
      { label: "被告数量", value: "defendantCount" },
      { label: "借据数量", value: "loanCount" },
      { label: "未还本金合计", value: "unpaidPrincipal" },
      { label: "未还利息合计", value: "unpaidInterest" },
      { label: "未还罚息合计", value: "unpaidPenalty" },
      { label: "未还复利合计", value: "unpaidCompound" },
      { label: "未还担保费合计", value: "unpaidGuaranteeFee" },
      { label: "未还违约金合计", value: "unpaidPenalty" },
      { label: "未还金额合计", value: "unpaidTotal" },
      { label: "逾期罚息利率浮动比例(%)", value: "penaltyRate" },
    ],
  },
  {
    label: "合同（借据维度）(自营)",
    value: "loanSelfList",
    children: [
      { label: "授信协议合同号", value: "creditNo" },
      { label: "授信协议合同名称", value: "creditName" },
      { label: "授信协议签订日期", value: "creditSignDate" },
      { label: "提款申请书合同号", value: "withdrawalLoanNo" },
      { label: "提款申请书合同名称", value: "withdrawalLoanName" },
      { label: "提款申请书签订日期", value: "withdrawalSignDate" },
      { label: "贷款用途", value: "loanPurpose" },
      { label: "借款人名称", value: "customerName" },
      { label: "放款金额", value: "loanAmount" },
      { label: "贷款起始日", value: "loanStartDate" },
      { label: "贷款到期日", value: "loanEndDate" },
    ],
  },
  {
    label: "合同（借据维度）(借新还旧)",
    value: "loanNewOldList",
    children: [
      { label: "借新还旧原提款申请书合同号", value: "originLoanNo" },
      { label: "提款申请书合同号", value: "withdrawalLoanNo" },
      { label: "提款申请书合同名称", value: "withdrawalLoanName" },
      { label: "提款申请书签订日期", value: "withdrawalSignDate" },
      { label: "借款人名称", value: "customerName" },
      { label: "放款金额", value: "loanAmount" },
      { label: "贷款起始日", value: "loanStartDate" },
      { label: "贷款到期日", value: "loanEndDate" },
      { label: "原贷款放款日期", value: "originLoanStartDate" },
      { label: "原贷放款金额", value: "originLoanAmount" },
    ],
  },
  {
    label: "合同（借据维度）（联合贷已回购）",
    value: "loanUnionList",
    children: [
      { label: "授信协议合同号（小雨点）", value: "creditNoXyd" },
      { label: "授信协议合同名称（小雨点）", value: "creditNameXyd" },
      { label: "授信协议签订日期（小雨点）", value: "creditSignDateXyd" },
      { label: "提款申请书合同号（小雨点）", value: "withdrawalLoanNoXyd" },
      {
        label: "提款申请书合同名称（小雨点）",
        value: "withdrawalLoanNameXyd",
      },
      {
        label: "提款申请书签订日期（小雨点）",
        value: "withdrawalSignDateXyd",
      },
      { label: "授信协议合同号（蓝海银行）", value: "creditNoLn" },
      { label: "授信协议合同名称（蓝海银行）", value: "creditNameLn" },
      { label: "授信协议签订日期（蓝海银行）", value: "creditSignDateLn" },
      {
        label: "提款申请书合同号（蓝海银行）",
        value: "withdrawalLoanNoLn",
      },
      {
        label: "提款申请书合同名称（蓝海银行）",
        value: "withdrawalLoanNameLn",
      },
      {
        label: "提款申请书签订日期（蓝海银行）",
        value: "withdrawalSignDateLn",
      },
      { label: "贷款用途", value: "loanPurpose" },
      { label: "借款人名称", value: "customerName" },
      { label: "放款金额", value: "loanAmount" },
      { label: "贷款起始日", value: "loanStartDate" },
      { label: "贷款到期日", value: "loanEndDate" },
      { label: "回购日期", value: "repurchaseDate" },
      { label: "回购本金", value: "repurchasePrincipal" },
      { label: "回购利息", value: "repurchaseInterest" },
      { label: "回购罚息", value: "repurchasePenalty" },
      { label: "回购复利", value: "repurchaseCompound" },
      { label: "回购总金额", value: "repurchaseTotalAmount" },
    ],
  },
  {
    label: "合同（借据维度）（助贷已回购）",
    value: "loanAssistList",
    children: [
      { label: "授信协议合同号", value: "creditNo" },
      { label: "授信协议合同名称", value: "creditName" },
      { label: "授信协议签订日期", value: "creditSignDate" },
      { label: "提款申请书合同号", value: "withdrawalLoanNo" },
      { label: "提款申请书合同名称", value: "withdrawalLoanName" },
      { label: "提款申请书签订日期", value: "withdrawalSignDate" },
      { label: "委托担保合同号", value: "guaranteeNo" },
      { label: "委托担保合同名称", value: "guaranteeNoName" },
      { label: "委托担保签订日期", value: "guaranteeSignDate" },
      { label: "贷款用途", value: "loanPurpose" },
      { label: "借款人名称", value: "customerName" },
      { label: "资金方全称", value: "funderFullName" },
      { label: "资金方简称", value: "funderShortName" },
      { label: "担保公司全称", value: "guaranteeFullName" },
      { label: "担保公司简称", value: "guaranteeShortName" },
      { label: "放款金额", value: "loanAmount" },
      { label: "贷款起始日", value: "loanStartDate" },
      { label: "贷款到期日", value: "loanEndDate" },
      { label: "回购日期", value: "repurchaseDate" },
      { label: "回购本金", value: "repurchasePrincipal" },
      { label: "回购利息", value: "repurchaseInterest" },
      { label: "回购罚息", value: "repurchasePenalty" },
      { label: "回购复利", value: "repurchaseCompound" },
      { label: "回购总金额", value: "repurchaseTotalAmount" },
    ],
  },
  {
    label: "主合同信息（自营）",
    value: "creditSelfList",
    children: [
      { label: "授信协议合同号", value: "creditNo" },
      { label: "授信协议合同名称", value: "creditName" },
      { label: "授信协议签订日期", value: "creditSignDate" },
      { label: "借据数量", value: "loanCount" },
    ],
  },
  {
    label: "主合同信息（联合贷已回购）",
    value: "creditUnionList",
    children: [
      { label: "授信协议合同号（小雨点）", value: "creditNoXyd" },
      { label: "授信协议合同名称（小雨点）", value: "creditNameXyd" },
      { label: "授信协议签订日期（小雨点）", value: "creditSignDateXyd" },
      { label: "借据数量", value: "loanCount" },
      { label: "授信协议合同号（蓝海银行）", value: "creditNoLn" },
      { label: "授信协议合同名称（蓝海银行）", value: "creditNameLn" },
      { label: "授信协议签订日期（蓝海银行）", value: "creditSignDateLn" },
    ],
  },
  {
    label: "主合同信息（助贷已回购）",
    value: "creditAssistList",
    children: [
      { label: "授信协议合同号", value: "creditNo" },
      { label: "授信协议合同名称", value: "creditName" },
      { label: "授信协议签订日期", value: "creditSignDate" },
      { label: "委托担保合同号", value: "guaranteeNo" },
      { label: "委托担保合同名称", value: "guaranteeNoName" },
      { label: "委托担保签订日期", value: "guaranteeSignDate" },
      { label: "借据数量", value: "loanCount" },
    ],
  },
  {
    label: "被告人(个人/企业+担保人)",
    value: "defendantList",
    children: [
      { label: "客户名称", value: "customerName" },
      { label: "性别", value: "gender" },
      { label: "民族", value: "nation" },
      { label: "出生年", value: "birthYear" },
      { label: "出生月", value: "birthMonth" },
      { label: "出生日", value: "birthDay" },
      { label: "证件号码", value: "idNumber" },
      { label: "身份证地址", value: "idAddress" },
      { label: "通讯地址", value: "contactAddress" },
      { label: "联系电话", value: "phone" },
      { label: "企业名称", value: "enterpriseName" },
      { label: "统一社会信用代码", value: "unifiedSocialCreditCode" },
      { label: "注册地址", value: "registeredAddress" },
      { label: "法定代表人姓名", value: "legalName" },
      { label: "法定代表人联系电话", value: "legalPhone" },
      { label: "担保人名称", value: "guarantorName" },
    ],
  },
];
